### ISSUE TITLE
Intermittent "NAN: value in Aquarius table for WQBattV_min

### ISSUE THREAD

**Issue by USGSminc** [SacArea-BayDeltaProjects/HydroRDITemplate#25]
For the newest program both OH4 and DLC are having the problem where the WQBattV_min will occasionally show a NAN value. It appears that the burst data median battery voltage is coming in fine. I have not looked further at this time.

**Comment by violetteta8** [comment]
I think we understand this now. It's because the "Minimum" function outputs an NAN if ANY of the values before the table output is an NAN. We know that sometimes the sonde doesn't respond appropriately at times, so that's probably the culprit. Maybe we consider taking that out of the AQ table if the NAN bothers us? Just wanted to comment here so we didn't forget what we learned.
