### ISSUE TITLE
Skip Scans

### ISSUE THREAD

**Issue by jehatfield** [SacArea-BayDeltaProjects/HydroRDITemplate#53]
Was reviewing the gage height data for SHG 11455276 and found that we are still getting small data gaps no larger than 30 minutes that I have seen. I checked in the velocity data and the skips are not happening so I think the issue is isolated to just the gage height data.. Thought I would ask for y'all to take a peek and see why the DCP is not collecting the punches. Look at early July 2019 for an example. Tho you can find these missing data points throughout the record. Thanks -JHat.

**Comment by violetteta8** [comment]
@jehatfield I see where you're missing single points in gage height. For clarification, that isn't a "Skipped Scan". A Skipped Scan is if the datalogger/instrumentation takes longer than our specified interval (1 minute), the datalogger can't restart it's processing until the top of the minute. So if the first scan took 61 seconds to process, the logger will sit idle for 59 seconds (missing the "second" scan) and restart the scan at the top of the third minute. The good news: Shag has 0 "Skipped Scans", so the timing of everything there is working properly.

Here's the next step: each gage height data point is an average of the previous 15 minutes. The problem is that the data table won't process a value if one of those values is an NAN. so if 1 out of 15 minutes had an NAN populate from the sensor, the logger won't average the other 14 and will produce an NAN that gets published. I'm going to turn on 1-min data to see that that is actually what's happening. If so, hopefully we can find a pattern or determine that there's a sensor problem(?).

PS. Thanks for using the "Issues" tool. When you use it, if you go to the right side of the dialogue box, there's an "Assignees" tab. If you would select Mark or me in that tab, that'd be helpful. That way it'll send us an email. Otherwise, it doesn't send an email.
